name = "Soberana Basics"
author = "roridev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44577ecef2c810f74e60d2f2c8270b6cf67f68c42a4864429c75734998e31737"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.2"
