name = "Soberana Extras"
author = "roridev"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c339e8f861f1998c137b43a851182247fd3e641964267518998ad35f90b42413"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.2"
