name = "Soberana Basics"
author = "roridev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92fba611cd2a97ceaff080483b856582cf7cb906b66e34e187ac1e9fbe3e38c3"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.2"
